name: "beeyond-CiCD"

services:
  frontend:
    image: abhisheksankhla121/beeyond-frontend:latest
    restart: always
    networks:
      - beeyond-network

  backend:
    image: abhisheksankhla121/beeyond-backend:latest
    restart: always
    environment:
      PORT: 5000
      DEV_ENVIROMENT_DATABASE_CONNECTION_STRING: mongodb://admin:admin@mongo:27017/abhishek?authSource=admin
      FRONTEND_URL: https://beeyondfrontend.fazalbazar.shop
      JWT_SECRET: super-secret-key-123
    depends_on:
      - mongo
    networks:
      - beeyond-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db:/data/db
    networks:
      - beeyond-network

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - beeyond-network

networks:
  beeyond-network:
    driver: bridge
